### ISSUE TITLE
System Update does not preserve /boot/config.txt changes (crossref)

### ISSUE THREAD

**Issue by xipmix** [volumio/Build#347]
Cross ref to volumio/Volumio2#1568

**Comment by gkkpch** [comment]
The problem is the following code in scripts/initramfs/init:
`if [ -e "/mnt/imgpart/config.txt.bak" ]; then

    print_msg "Restoring custom config.txt content"
    I2S=`sed -n -e '/#### Volumio i2s setting below: do not alter ####/,$p' /mnt/imgpart/config.txt.bak`
    echo "" >> /boot/config.txt
    echo "$I2S" >> /boot/config.txt
    rm /mnt/imgpart/config.txt.bak

  fi`

As shown, it does not really restore config.txt from a backup, it just takes the DAC DT overlay settings from the old config and adds it to the one from the update.
There is no perfect way to solve this (at least, I don't see one yet).
Option 1, taking the update, will always preserve a bootable system as it was tested that way), but some customisation settings could be missing (new or changed params).
Option 2, using the backup settings, will only work, as long as there was no need in the new update to add or change a param setting. Therefore this has potential for boot failure.

And improvement of option 1 could be a merge: all parameter settings from config.txt.bak are added to the end of config.txt in case they were not already present there.
This would automatically add the DAC settings, no need to search with "sed" and add them.
However, this option is not 100% proof in cases where a value was changed during customising or because the new volumio version required it to be.

**Comment by swinokur** [comment]
You could do option #1, but you should then move config.txt to another name (config.txt.saved, etc). Currently the existing config.txt is backed up during the first phase of upgrade, but then for some reason the backup is deleted. So, if someone has made configurations and not remembered / recorded what they did, then those changes will be lost through the upgrade procedure.

**Comment by gvolt** [comment]
What do you think about that:

As recently posted in the [Volumio forum](https://volumio.org/forum/config-txt-overwritten-each-system-update-t10667.html#p53111) there is already an "include" option for the config.txt ([https://www.raspberrypi.org/documentation/configuration/config-txt/misc.md](https://www.raspberrypi.org/documentation/configuration/config-txt/misc.md)). The content of the file specified will then be inserted into the config.txt. This of course would require Volumio incorporating the "include" option into the default config.txt file.

In order to ensure a safe reboot after an update the include option could be commented out at the first boot. On the dev page of the webinterface a switch could be added to activate (uncomment) the include option in the config.txt file.

**Comment by gkkpch** [comment]
Yes, let us have a closer look at your suggestion and see if we can solve this for the Tinker S, which also uses a “config.txt” type of early boot config  (but calls it hw-intf.conf) in a similar way. 
This would allow us to implement it in a more generic way....
Good one though!

**Comment by gkkpch** [comment]
I just checked u-boot for Asus Tinkerboard and unfortunately the allowed name/value pairs are fixed and hardcoded, so an "include" option for a sub-config is not possible for the time being. This means we need two solutions, one for PI and one for Tinker/Tinker S. We need to keep it simple.
When we do this, I suggest Volumio does not start with an include option in config.txt at all, so there is nothing to delete at first boot. It would be up to the  tinkerer to insert an include for a file with the data he needs. What Volumio could do after an update is simply check the backup for an "include"-option and copy that line to the end of the new config.txt 
DON'T add more than one include as we don't want to blow up our initramfs with a complete config parser with all it's possible combinations.....

**Comment by gvolt** [comment]
Great you already checked it. I did not have the time to dig deeper and had problems to find documentation of the hw_intf.conf, too. It's indeed unfortunate that there is no include option :(.

Regarding RasPi I would suggest to put a commented out include option with a given path and filename into the vanilla config.txt:

`#include /path/to/custom_config.txt`

That way there would be nothing to delete on first start. The tinkerer would have to fill the predetermined file and remove the comment statement (#). And if it would be communicated that the given file will be the only one which would not be affected by an update I guess that will prevent inflating the config.txt with multiple include options.

Also a check for (an) include option(s) would not be necessary. The new vanilla config.txt with the "#include ..." option would just be put into place. This would also have the following advantage: The single include option is commented out again and the tinkerer has the opportunity to check if the content of the customconfig.txt is still appropriate. If (after an update) the include option would just be copied from the backed up config.txt into the new config.txt this would involve the risk to render the system unbootable.

All IMHO of course :)

**Comment by gkkpch** [comment]
Meaning we would not need to do anything for Tinker and just add the #include line to the default PI config. 
Actually very good, I think this will work without any changes for the update procedure.
Any comment from @Michelangelo?

**Comment by gvolt** [comment]
> Meaning we would not need to do anything for Tinker and just add the #include line to the default PI config.

Exactly!

Additionally one could consider adding a switch to the dev page (http://volumio.local/dev) which would "activate" the include option so the user would not have to modify the config.txt manually. But that would lead to a dev page for the RasPI differing from the "standard" dev page. I could easily understand if that might not be desired.

**Comment by gvolt** [comment]
Yes, for sure, complete overkill especially in the case you mentioned... it is more of a convenience thing after the include file has already been finished, the system is working and you just want to reactivate it without doing changes after a Volumio update has taken place. Still a little overkill ;)
