### ISSUE TITLE
Cannot build on Arch

### ISSUE THREAD

**Issue by thxrben** [volumio/Build#523]
I cannot build Volumio using Arch.

Due to the use of apt-key, the installation fails in line 191 of build.sh:

```
[ .... ] Running Volumio Image Builder -  
[ .. ] Checking whether we are running as root 
[ .. ] Creating log directory 
[ .. ] Setting default Volumio variant 
[ .... ] Creating arm rootfs  
[ .... ] Patching multistrap config to point to Raspbian sources  
[ .. ] Raspbian multistrap config created at arm-raspbian.conf 
[ .... ] Setting up Multistrap environment  
[ .. ] Preparing rootfs apt-config 
[ .. ] Adding SecureApt keys to rootfs 
./build.sh: Zeile 191: apt-key: Kommando nicht gefunden.
```

**Comment by gkkpch** [comment]
Thorben,you can only build Volumio on Debian Buster (or newer)  or Ubuntu 20.04 (or newer)On 5 Aug 2023, at 12:38, Thorben ***@***.***> wrote:﻿
I cannot build Volumio using Arch.
Due to the use of apt-key, the installation fails in line 191 of build.sh:
[ .... ] Running Volumio Image Builder -  
[ .. ] Checking whether we are running as root 
[ .. ] Creating log directory 
[ .. ] Setting default Volumio variant 
[ .... ] Creating arm rootfs  
[ .... ] Patching multistrap config to point to Raspbian sources  
[ .. ] Raspbian multistrap config created at arm-raspbian.conf 
[ .... ] Setting up Multistrap environment  
[ .. ] Preparing rootfs apt-config 
[ .. ] Adding SecureApt keys to rootfs 
./build.sh: Zeile 191: apt-key: Kommando nicht gefunden.

**Comment by gkkpch** [comment]
You are also opening an issue on repository "volumio/Build", which is unused and unsupported since end of 2021. In case you are serious about building your own (without myVolumio as you cannot do that yourself), then refer to "volumio/volumio3-os" instead.
As said, on Debian 10 or current Ubuntu only. Please read the README.md, it clearly mentions Debian Buster, Ubuntu is a later bonus. 
So don't open issues when there aren't any.

**Comment by thxrben** [comment]
The old repo was more ore less intended. Still on 2.917, which still has the autostart plugin while the support for V3 hasnt been worked on for a long time.

To support building only on certain distros is your decision, but it sucks since the tools are (generally) available on all distros. Especially hard-coding a package manager isnt a nice thing for compatibility. But okay, setting up a docker with Debian shouldn't be an issue.

> So don't open issues when there aren't any.

Well, the issue is there. If it wasnt, I wouldn't open it. I don't know shell scripts extensively enough to rewrite it, otherwise I would've. Would be nice to "just" rely on the requirements, or just rather to skip the installation if it isn't Debian or Ubuntu. 

Thanks for you time to reply :)

**Comment by gkkpch** [comment]
Install a VM with debian or ubuntu and you're fine.
Volumio does not claim anywhere that the build runs on any distro, so why complain about it.
The fact that you have a problem with it, is not a Volumio build issue to report, but yours to solve.

**Comment by thxrben** [comment]
Never said it was your problem, to be fair, I have overread the Debian/Ubuntu part.

Nontheless, it just sucks to have a script which isnt cross-compatible. I dont say that you are in the wrong, it just sucks.
