### ISSUE TITLE
Volumio2 RC1 (volumio-0.861-2016-03-25-pi) IP address issue (fix IP configured in the image)

### ISSUE THREAD

**Issue by apinner** [volumio/Build#54]
Referenced: https://github.com/volumio/Volumio2/issues/303

**Comment by Alexqw** [comment]
This can be fixed by simply reverting all of 07c4b8cf3a7207c15f5ba6018f5376c383027dad

If you want to keep a fallback IP, just in case, then I recommend two things

1. Remove the timeout so that it uses the default of 60. 10 seconds, for some reason, is too low for my network/device, and I always end up with this static IP.
2. 192.168.8.8 is a suboptimal default, as I don't know of any consumer routers that default to the .8 subnet. In my experience, most home networks default to 192.168.1.* (or 0.*) with a subnet mask of 255.255.255.0. Choosing something in a subnet that most can't access without jumping through configuration hoops defeats the purpose of this fall-back convenience.

---Alex
